pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: ombi-dev

  test:
    image: docker
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    commands:
      - apk add --no-cache curl
      - CON_NAME=$(docker run -dt ombi-dev)
      - timeout -t 45 -- docker logs -f $$CON_NAME | cat &
      - sleep 45
      - IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $$CON_NAME)
      - if [ -z "$IP" ]; then
            echo "The container exited.. sadpanda";
            docker inspect --format='{{.State.ExitCode}}' $$CON_NAME;
            docker rm $$CON_NAME
            exit 25;
        fi
      - curl -L --retry-max-time 30 --max-time 5 --retry 10 --retry-delay 5 --retry-connrefused $IP:5000 > /dev/null
      - docker kill $$CON_NAME
      - docker rm $$CON_NAME


  publish:
    image: spritsail/docker-publish
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    when: { branch: [ master, pass ], event: [ push, tag, deployment ] }
    from: ombi-dev
    repo: spritsail/ombi
    tags:
      - 'latest'
      - '%label: io.spritsail.version.ombi'

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
