---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: spritsail/ombi

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    curl: :5000
    repo: spritsail/ombi
    delay: 10
    verbose: true

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    repo: spritsail/ombi
    tags:
    - 'beta'
    - '%label io.spritsail.version.ombi | %auto | %prefix beta'
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - beta
    event:
    - push
---
kind: signature
hmac: 561dc4f42e2f24ccae29f9f64039cdf6ba00b08fca0654d8c7a9a3ee3b29ad51

...
